version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'typescript-eslint'
      tanstack:
        patterns:
          - '@tanstack/*'
      dnd-kit:
        patterns:
          - '@dnd-kit/*'
      tailwind:
        patterns:
          - 'tailwindcss'
          - 'tailwindcss-*'
          - 'postcss'
          - 'autoprefixer'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
